import numpy as np
import pandas as pd

from src.config import (
    PROCESSED_DATA_DIR,
    DEFAULT_USEFUL_SENSORS,
    create_directories,
)


WINDOWS = [5, 10, 20]


def add_temporal_features(
    df: pd.DataFrame,
    sensors=None,
):

    if sensors is None:
        sensors = DEFAULT_USEFUL_SENSORS

    df = df.copy()

    # Always sort before creating
    # time-series features.
    df = df.sort_values(
        ["unit", "cycle"]
    ).reset_index(drop=True)

    grouped = df.groupby(
        "unit",
        group_keys=False,
    )

    for sensor in sensors:

        # --------------------------------------------------
        # First-order difference
        # --------------------------------------------------

        df[f"{sensor}_diff"] = (
            grouped[sensor]
            .diff()
            .fillna(0)
        )

        # --------------------------------------------------
        # Rolling statistics
        # --------------------------------------------------

        for window in WINDOWS:

            df[
                f"{sensor}_rolling_mean_{window}"
            ] = (
                grouped[sensor]
                .rolling(
                    window=window,
                    min_periods=1,
                )
                .mean()
                .reset_index(
                    level=0,
                    drop=True,
                )
            )

            df[
                f"{sensor}_rolling_std_{window}"
            ] = (
                grouped[sensor]
                .rolling(
                    window=window,
                    min_periods=1,
                )
                .std()
                .reset_index(
                    level=0,
                    drop=True,
                )
                .fillna(0)
            )

    return df


def add_cycle_features(df):

    df = df.copy()

    # Relative position in the engine's life.
    max_cycle = (
        df.groupby("unit")["cycle"]
        .transform("max")
    )

    df["cycle_ratio"] = (
        df["cycle"] / max_cycle
    )

    return df


def add_degradation_features(df):

    df = df.copy()

    sensors = DEFAULT_USEFUL_SENSORS

    # Cross-sensor relationships
    # that may capture system-level degradation.

    df["thermal_load"] = (
        df["s4"]
        * df["s15"]
    )

    df["mechanical_stress"] = (
        df["s11"]
        * df["s20"]
    )

    df["pressure_ratio"] = (
        df["s4"]
        / (df["s3"] + 1e-8)
    )

    df["sensor_mean"] = (
        df[sensors]
        .mean(axis=1)
    )

    df["sensor_std"] = (
        df[sensors]
        .std(axis=1)
    )

    return df


def build_features():

    create_directories()

    input_path = (
        PROCESSED_DATA_DIR
        / "train_rul.csv"
    )

    output_path = (
        PROCESSED_DATA_DIR
        / "train_features.csv"
    )

    df = pd.read_csv(
        input_path
    )

    print("=" * 60)
    print("TEMPORAL FEATURE ENGINEERING")
    print("=" * 60)

    print(
        f"Input rows: {len(df):,}"
    )

    print(
        f"Base sensors: "
        f"{len(DEFAULT_USEFUL_SENSORS)}"
    )

    # 1. Temporal features
    df = add_temporal_features(
        df
    )

    # 2. Cycle features
    df = add_cycle_features(
        df
    )

    # 3. Cross-sensor features
    df = add_degradation_features(
        df
    )

    # Prevent accidental infinities.
    df.replace(
        [np.inf, -np.inf],
        np.nan,
        inplace=True,
    )

    # Fill any remaining missing
    # values generated by rolling operations.
    df.ffill(
        inplace=True
    )

    df.bfill(
        inplace=True
    )

    df.to_csv(
        output_path,
        index=False,
    )

    print(
        f"\nOutput rows: "
        f"{len(df):,}"
    )

    print(
        f"Output columns: "
        f"{len(df.columns)}"
    )

    print(
        f"\nSaved to:\n{output_path}"
    )

    return df


if __name__ == "__main__":

    build_features()